services:
  logql-proxy:
    build: .
    ports:
      - "3100:3100"
    environment:
      PROXY_VLOGS_URL: http://victorialogs:9428
      PROXY_LIMITS_MAXMEMORYMB: "512"
    depends_on:
      - victorialogs
    restart: unless-stopped

  victorialogs:
    image: victoriametrics/victoria-logs:latest@sha256:47b820890d64c4575a2a0a46415dcd8a4fd59a0f1fcd6a377693d7aea639442e
    ports:
      - "9428:9428"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest@sha256:3fd54ae1214669f8355f065ec9f6445d5279a3d77095ab048ca045685272429b
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "logsExplore"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - logql-proxy
    restart: unless-stopped

volumes:
  grafana-data: {}
