services:
  logql-proxy:
    build: .
    ports:
      - "3100:3100"
    environment:
      PROXY_VLOGS_URL: http://victorialogs:9428
      PROXY_LIMITS_MAXMEMORYMB: "512"
    depends_on:
      - victorialogs
    restart: unless-stopped

  victorialogs:
    image: victoriametrics/victoria-logs:latest@sha256:251121fa882af99b95ba0c230a4a2f412ea602d2698c64a96c58dc9842bb755d
    ports:
      - "9428:9428"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest@sha256:b28bae15e219c998fb0e0424ed724930cc61b1f61fb404d47c862f9a23f9e572
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "logsExplore"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - logql-proxy
    restart: unless-stopped

volumes:
  grafana-data: {}
